### ISSUE TITLE
Truth maintenance documentation update

### ISSUE THREAD

**Issue by WilliamParker** [oracle-samples/clara-site#13]
1. Once https://github.com/cerner/clara-examples/pull/12 is merged I suggest that the truth maintenance page link to that example.
2. I propose that we add a sentence to the end of the second to last paragraph so it would be like 

"Truth maintenance is transitive. So if any rules used the PremierCustomer fact to infer further knowledge, that inference would also be retracted.  As a result we can treat rules that consistently use truth maintenance as purely declarative statements."

3. I believe that the Truth Maintenance page link should be moved from the "Advanced Topics" guide to the "Developer Guide" section.  The other subjects in "Advanced Topics" are something of niche subjects and it is very possible to write rules without understanding of them, but the idea that rules are logical relationships rather than procedural code is very much a foundational idea of rules engines in my opinion and in my experience it isn't obvious to many people learning about rules engines for the first time.

**Comment by mrrodriguez** [comment]
>I believe that the Truth Maintenance page link should be moved from the "Advanced Topics" guide to the "Developer Guide" section. The other subjects in "Advanced Topics" are something of niche subjects and it is very possible to write rules without understanding of them, but the idea that rules are logical relationships rather than procedural code is very much a foundational idea of rules engines in my opinion and in my experience it isn't obvious to many people learning about rules engines for the first time.

I agree with you that TMS is a first-class subject in Clara and I wouldn't consider it "Advance Topics".

Interestingly, though in general, rules engines have not had TMS as the default.  The default seems to be unconditional insertion, which results in order-dependent rules and non-declarative rules.  I find that to be odd.  I'm glad that is not the case in Clara.  
I only say this because you seemed to imply that TMS is a "foundational idea of rules engines".  I actually have seen a lot of other rules engines where people tend to not use TMS as much as you'd think.  It isn't always idiomatic and a lot of the reference literature on rules engines do not even bring it up.

+1 to Clara making it idiomatic and +1 to your suggestion of the TMS topic being a central point of documentation in Clara though.

**Comment by WilliamParker** [comment]
On the distinction between Clara and other rules engine, good point.  That only increases the importance of making it clear in the documentation though. :)

**Comment by rbrush** [comment]
+1 for these changes.

**Comment by WilliamParker** [comment]
PR at https://github.com/cerner/clara-site/pull/15

**Comment by WilliamParker** [comment]
Closing since I've merged the PR.
