### ISSUE TITLE
Site references artifacts that don't exist due to transfer of ownership

### ISSUE THREAD

**Issue by KevinGreene** [oracle-samples/clara-site#9]
At http://www.clara-rules.org/docs/firststeps/, the instructions for adding Clara to a project list `[com.cerner/clara-rules "0.12.0"]` as the artifact, but that doesn't exist anywhere.

Updating to 13.0-RC4, however, isn't easily done because as far as I can tell, those API docs aren't available at http://www.clara-rules.org/apidocs/*

I'd recommend either publishing the given artifact, or updating the API docs to 13.0-RC4.

**Comment by WilliamParker** [comment]
@KevinGreene releases prior to 13.0-RC4 are under org.toomuchcode, not com.cerner.  See https://clojars.org/org.toomuchcode/clara-rules

We recently moved clara-rules to Cerner's corporate GitHub organization, hence the change.  There is a blog post on this at http://engineering.cerner.com/blog/clara-rules-joins-cerner-open-source/ We'll look at fixing these inconsistencies.

**Comment by KevinGreene** [comment]
@WilliamParker Yup, understood!

Perhaps I wasn't as clear, but the issue I have is that the introduction documentation is wrong. It references `[com.cerner/clara-rules "0.12.0"]`, but as you mentioned that doesn't exist. 

Originally I was going to just update `_config.yml` to point to the correct release, but I think it's confusing to point to one version in the docs, but link to API docs for a different version.

However, it seems the API docs aren't automatically generated with each release, as http://www.clara-rules.org/apidocs/0.12.0/clojure exists, but http://www.clara-rules.org/apidocs/0.13.0-RC4/clojure does not.

So, I didn't want to update the config.yml, but as a result the "first steps" someone takes with Clara is bound to be an error message informing them that `[com.cerner/clara-rules "0.12.0"]`, the suggested version on the website, doesn't exist.

**Comment by rbrush** [comment]
I hadn't re-generated the Clojure or JavaDocs for the 0.13 series since I thought of them more as release candidates rather than releases, but it probably makes sense to go ahead and do so given the transfer of the project. 

Note that there is a gen_api_docs script in this project (See https://github.com/cerner/clara-site/blob/gh-pages/gen_api_docs.sh), which given the path to clara-rules and a version (e.g. 0.13.0-RC4), will generate the docs and copy them to the right place in the clara-site project, so they can then be simply committed and visible on the site. Once that's done, changing the _config.yml version to 0.13.0-RC4 will get everything pointed at the right place.

I'm happy to do this myself, but wanted to share this the history and presence of the script with the group.

**Comment by rbrush** [comment]
Alright, I went ahead and generated the doc for 0.13.0-RC4 and updated the config accordingly, which is now reflected on the site. Thanks for letting us know about the discrepancy!

**Comment by rbrush** [comment]
Also, closing the issue now since this is taken care of. We can re-open if I'm missing anything.

**Comment by KevinGreene** [comment]
Thanks for the quick fix! As far as I can tell everything looks good.
